export const iconClasses = [
    // Frutas
    "fi fi-sr-apple-whole",
    "fi fi-rr-grape",
    "fi fi-sr-cherry",
    "fi fi-sr-strawberry",
    "fi fi-sr-lemon",
    "fi fi-sr-peach",
    "fi fi-sr-citrus",
    "fi fi-sr-pineapple-alt",
    "fi fi-sr-banana",
    "fi fi-sr-kiwi-fruit",
    "fi fi-ss-coconut",
    "fi fi-sr-pear",
    "fi fi-sr-olive",
    "fi fi-sr-mango",
    "fi fi-sr-melon",
    "fi fi-sr-acorn",
    "fi fi-ss-avocado",
    "fi fi-sr-blueberries",

    // Verduras
    "fi fi-sr-leaf",
    "fi fi-sr-tree",
    "fi fi-sr-leafy-green",
    "fi fi-sr-carrot",
    "fi fi-sr-broccoli",
    "fi fi-sr-radish",
    "fi fi-ss-potato",
    "fi fi-ss-pepper-alt",
    "fi fi-sr-aubergine",
    "fi fi-ss-cucumber",
    "fi fi-sr-peapod",
    "fi fi-ss-pumpkin-alt-2",
    "fi fi-bs-onion",
    "fi fi-sr-tomato",

    // Carnes y Animales
    "fi fi-sr-meat",
    "fi fi-sr-steak",
    "fi fi-sr-cow-alt",
    "fi fi-rr-cow-alt",
    "fi fi-ss-sheep",
    "fi fi-bs-pig-face",
    "fi fi-ss-bacon",
    "fi fi-ss-cheese",
    "fi fi-sr-horse-head",
    "fi fi-sr-fish",
    "fi fi-sr-fish-bones",
    "fi fi-sr-shrimp",
    "fi fi-ss-egg",

    // Otros
    "fi fi-ss-bottle",
];